### PR TITLE
Added initial verison of github issue export

### PR DESCRIPTION
**Pull request by WtfJoke**
Represents my work in progress. 

What I did:
- Workitemtypes are represented as labels
- Numbers cannot be set through the api (As a tradeoff I included them in the title --> Number:)
- HTML Body text gets interpreted well
- Noticed that title looks strange when '&' is included

What I didnt do:
- JUnit-Tests (They'll follow soon, I'll promise :angel:)
- An additional mappingmap which maps the default attributes to githubattributes (not sure if necessary)

### CODE REVIEW

**Comment by romixch** [comment]
We should use the same style guilde. I suggest to use this one:
https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml

**Comment by romixch** [comment]
Merged it into master. Although I would like to make the migration process repeatable as many times as I want. As far as I understand it, this would create always a new issue.

**Comment by romixch** [comment]
Like the idea of checking if the exporter is configured. We could do it for the importer too.

**Comment by WtfJoke** [comment]
> Although I would like to make the migration process repeatable as many times as I want. As far as I understand it, this would create always a new issue.

Yep, that was still an open point on my to do list, but forgot to mention it.

**Pull request closed without merging**
